/**
 * GENERATED by tools/optimize.js --implement — 2026-08-24T21:08:48.519Z
 * weights: engage=1,discovery=1,declusterMean=0.5
 * sweep: score 1.989 over 100 configs × 5 repeats
 * verification: 2.325 vs baseline 2.500 on 8 fresh seeds
 * Hand-edits are overwritten by the next --implement run.
 */
export const TUNING_OVERRIDES = {
    CONFIG: {
        EXPLORE_VENTURE_WEIGHT: 0.215,
        CONVOY_CROWD_LIMIT: 9.5325,
        CONVOY_JOIN_RANGE: 8.8596,
        EXPLORE_RADIUS: 12.9383,
        EXPLORE_SAMPLES: 11,
        EXPLORE_INTERVAL: 1.0056,
        "SIGNAL_HALFLIVES.trail": 12.1721,
        "SIGNAL_HALFLIVES.recruit": 1.3199,
        SIGNAL_ALARM_STRENGTH: 5.6791,
        SIGNAL_ALARM_RESPONSE_RADIUS: 14,
        SIGNAL_TRAIL_DISTANCE_FACTOR: 0.0945,
    },
    VEHICLES: {
        "drone.personalSpace": 1.7192,
        "squad.personalSpace": 0.8165,
    },
};
