/**
 * Deterministic regeneration of js/config/swarm.js from the tunables
 * table plus adopted values.  The adoption tool owns this file's format
 * wholesale — no hand-edited literals, no formatting fights.
 */

/** Render the complete js/config/swarm.js module text. */
export function renderSwarmConfig(tunables, values) {
    const entries = tunables.map((t) => {
        const value = values[t.key] ?? t.value;
        return `    { key: ${JSON.stringify(t.key)}, value: ${fmtNum(value)}, min: ${fmtNum(t.min)}, max: ${fmtNum(t.max)}, doc: ${JSON.stringify(t.doc)} },`;
    });
    return `/**
 * Swarm tunables — every parameter that steers the colony-insect AI.
 *
 * This file is MACHINE-REGENERATED by tools/adopt.js from the tunables
 * table: keys, ranges, and docs are the schema; the \`value\` fields are
 * the currently adopted tuning.  Hand edits are fine — adoption only
 * ever rewrites \`value\` — but prefer adopting verified values.
 *
 * The game assembles SWARM defaults from this table,
 * Game.settings.tuning overrides any entry per match, the sandbox
 * generates its sliders from it, and the sweep optimizer samples within
 * [min, max].  Adding a tunable is ONE LINE here — nothing else needs
 * to know.
 *
 * Signal semantics (see js/ai/swarm/):
 *   trail    — weak crumbs every moving unit leaves (wander substrate)
 *   route    — a discoverer's walked path, lit when it personally sights
 *              an objective; shorter journeys lay stronger routes,
 *              followers reinforce their own paths, stale routes fade
 *   alarm    — deposited by a LIVING victim while recently hit; vanishes
 *              with the victim (no rallying to a corpse)
 *   food     — deposited on discovered, still-alive objectives
 *   visited  — exploration memory; retreading is repelled, so the swarm
 *              spreads out instead of blobbing at home
 */
export const SWARM_TUNABLES = Object.freeze([
${entries.join("\n")}
]);

/** Default swarm configuration assembled from the tunables table. */
export const SWARM = Object.freeze(Object.fromEntries(SWARM_TUNABLES.map((t) => [t.key, t.value])));
`;
}

/** Compact, round-trip-safe number formatting. */
function fmtNum(n) {
    const s = String(Math.round(n * 10000) / 10000);
    return s;
}
